In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/top-10000-spotify-songs-1960-now/top_10000_1960-now.csv

In [2]:
df = pd.read_csv('/kaggle/input/top-10000-spotify-songs-1960-now/top_10000_1960-now.csv')

In [3]:
pd.set_option('display.max_columns',None)

In [4]:
df.head()

,Track URI,Track Name,Artist URI(s),Artist Name(s),Album URI,Album Name,Album Artist URI(s),Album Artist Name(s),Album Release Date,Album Image URL,Disc Number,Track Number,Track Duration (ms),Track Preview URL,Explicit,Popularity,ISRC,Added By,Added At,Artist Genres,Danceability,Energy,Key,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Time Signature,Album Genres,Label,Copyrights
0,spotify:track:1XAZlnVtthcDZt2NI1Dtxo,Justified & Ancient - Stand by the Jams,spotify:artist:6dYrdRlNZSKaVxYg5IrvCH,The KLF,spotify:album:4MC0ZjNtVP1nDD5lsLxFjc,Songs Collection,spotify:artist:6dYrdRlNZSKaVxYg5IrvCH,The KLF,1992-08-03,https://i.scdn.co/image/ab67616d0000b27355346b...,1,3,216270,NaN,False,0,QMARG1760056,spotify:user:bradnumber1,2020-03-05T09:20:39Z,"acid house,ambient house,big beat,hip house",0.617,0.872,8.0,-12.305,1.0,0.0480,0.0158,0.112000,0.4080,0.504,111.458,4.0,NaN,Jams Communications,"C 1992 Copyright Control, P 1992 Jams Communic..."
1,spotify:track:6a8GbQIlV8HBUW3c6Uk9PH,I Know You Want Me (Calle Ocho),spotify:artist:0TnOYISbd1XYRBk9myaseg,Pitbull,spotify:album:5xLAcbvbSAlRtPXnKkggXA,Pitbull Starring In Rebelution,spotify:artist:0TnOYISbd1XYRBk9myaseg,Pitbull,2009-10-23,https://i.scdn.co/image/ab67616d0000b27326d73a...,1,3,237120,https://p.scdn.co/mp3-preview/d6f8883fc955cb0e...,False,64,USJAY0900144,spotify:user:bradnumber1,2021-08-08T09:26:31Z,"dance pop,miami hip hop,pop",0.825,0.743,2.0,-5.995,1.0,0.1490,0.0142,0.000021,0.2370,0.800,127.045,4.0,NaN,Mr.305/Polo Grounds Music/J Records,"P (P) 2009 RCA/JIVE Label Group, a unit of Son..."
2,spotify:track:70XtWbcVZcpaOddJftMcVi,From the Bottom of My Broken Heart,spotify:artist:26dSoYclwsYLMAKD3tpOr4,Britney Spears,spotify:album:3WNxdumkSMGMJRhEgK80qx,...Baby One More Time (Digital Deluxe Version),spotify:artist:26dSoYclwsYLMAKD3tpOr4,Britney Spears,1999-01-12,https://i.scdn.co/image/ab67616d0000b2738e4986...,1,6,312533,https://p.scdn.co/mp3-preview/1de5faef947224dc...,False,56,USJI19910455,spotify:user:bradnumber1,2021-08-08T09:26:31Z,"dance pop,pop",0.677,0.665,7.0,-5.171,1.0,0.0305,0.5600,0.000001,0.3380,0.706,74.981,4.0,NaN,Jive,P (P) 1999 Zomba Recording LLC
3,spotify:track:1NXUWyPJk5kO6DQJ5t7bDu,Apeman - 2014 Remastered Version,spotify:artist:1SQRv42e4PjEYfPhS0Tk9E,The Kinks,spotify:album:6lL6HugNEN4Vlc8sj0Zcse,"Lola vs. Powerman and the Moneygoround, Pt. On...",spotify:artist:1SQRv42e4PjEYfPhS0Tk9E,The Kinks,2014-10-20,https://i.scdn.co/image/ab67616d0000b2731e7c53...,1,11,233400,https://p.scdn.co/mp3-preview/c4df3a832509cc55...,False,42,GB5KW1499822,spotify:user:bradnumber1,2021-08-08T09:26:31Z,"album rock,art rock,british invasion,classic r...",0.683,0.728,9.0,-8.920,1.0,0.2590,0.5680,0.000051,0.0384,0.833,75.311,4.0,NaN,Sanctuary Records,"C © 2014 Sanctuary Records Group Ltd., a BMG C..."
4,spotify:track:72WZtWs6V7uu3aMgMmEkYe,You Can't Always Get What You Want,spotify:artist:22bE4uQ6baNwSHPVcDxLCe,The Rolling Stones,spotify:album:0c78nsgqX6VfniSNWIxwoD,Let It Bleed,spotify:artist:22bE4uQ6baNwSHPVcDxLCe,The Rolling Stones,1969-12-05,https://i.scdn.co/image/ab67616d0000b27373d927...,1,9,448720,NaN,False,0,USA176910100,spotify:user:bradnumber1,2021-08-08T09:26:31Z,"album rock,british invasion,classic rock,rock",0.319,0.627,0.0,-9.611,1.0,0.0687,0.6750,0.000073,0.2890,0.497,85.818,4.0,NaN,Universal Music Group,"C © 2002 ABKCO Music & Records Inc., P ℗ 2002 ..."

In [5]:
df = df[['Track Name','Artist Name(s)','Album Name','Album Image URL','Track Preview URL','Artist Genres','Label']]

In [6]:
df.head()

,Track Name,Artist Name(s),Album Name,Album Image URL,Track Preview URL,Artist Genres,Label
0,Justified & Ancient - Stand by the Jams,The KLF,Songs Collection,https://i.scdn.co/image/ab67616d0000b27355346b...,NaN,"acid house,ambient house,big beat,hip house",Jams Communications
1,I Know You Want Me (Calle Ocho),Pitbull,Pitbull Starring In Rebelution,https://i.scdn.co/image/ab67616d0000b27326d73a...,https://p.scdn.co/mp3-preview/d6f8883fc955cb0e...,"dance pop,miami hip hop,pop",Mr.305/Polo Grounds Music/J Records
2,From the Bottom of My Broken Heart,Britney Spears,...Baby One More Time (Digital Deluxe Version),https://i.scdn.co/image/ab67616d0000b2738e4986...,https://p.scdn.co/mp3-preview/1de5faef947224dc...,"dance pop,pop",Jive
3,Apeman - 2014 Remastered Version,The Kinks,"Lola vs. Powerman and the Moneygoround, Pt. On...",https://i.scdn.co/image/ab67616d0000b2731e7c53...,https://p.scdn.co/mp3-preview/c4df3a832509cc55...,"album rock,art rock,british invasion,classic r...",Sanctuary Records
4,You Can't Always Get What You Want,The Rolling Stones,Let It Bleed,https://i.scdn.co/image/ab67616d0000b27373d927...,NaN,"album rock,british invasion,classic rock,rock",Universal Music Group

In [7]:

df['Artist Name(s)1'] = df['Artist Name(s)'].str.replace(' ','')

In [8]:
df['Album Name'] = df['Album Name'].str.replace(' ','')
df['Artist Genres'] = df['Artist Genres'].apply(lambda x: str(x).split(','))

In [9]:
df['Label'] = df['Label'].str.replace(' ','')

In [10]:
df['Artist Name(s)1'] = df['Artist Name(s)'].apply(lambda x: [x])
df['Album Name'] = df['Album Name'].apply(lambda x: [x])
df['Label'] = df['Label'].apply(lambda x: [x])

In [11]:
df.head()

,Track Name,Artist Name(s),Album Name,Album Image URL,Track Preview URL,Artist Genres,Label,Artist Name(s)1
0,Justified & Ancient - Stand by the Jams,The KLF,[SongsCollection],https://i.scdn.co/image/ab67616d0000b27355346b...,NaN,"[acid house, ambient house, big beat, hip house]",[JamsCommunications],[The KLF]
1,I Know You Want Me (Calle Ocho),Pitbull,[PitbullStarringInRebelution],https://i.scdn.co/image/ab67616d0000b27326d73a...,https://p.scdn.co/mp3-preview/d6f8883fc955cb0e...,"[dance pop, miami hip hop, pop]",[Mr.305/PoloGroundsMusic/JRecords],[Pitbull]
2,From the Bottom of My Broken Heart,Britney Spears,[...BabyOneMoreTime(DigitalDeluxeVersion)],https://i.scdn.co/image/ab67616d0000b2738e4986...,https://p.scdn.co/mp3-preview/1de5faef947224dc...,"[dance pop, pop]",[Jive],[Britney Spears]
3,Apeman - 2014 Remastered Version,The Kinks,"[Lolavs.PowermanandtheMoneygoround,Pt.One+Perc...",https://i.scdn.co/image/ab67616d0000b2731e7c53...,https://p.scdn.co/mp3-preview/c4df3a832509cc55...,"[album rock, art rock, british invasion, class...",[SanctuaryRecords],[The Kinks]
4,You Can't Always Get What You Want,The Rolling Stones,[LetItBleed],https://i.scdn.co/image/ab67616d0000b27373d927...,NaN,"[album rock, british invasion, classic rock, r...",[UniversalMusicGroup],[The Rolling Stones]

In [12]:
df['tags'] = df['Artist Name(s)1']+df['Album Name']+df['Artist Genres']+df['Label']

In [13]:
df.head()

,Track Name,Artist Name(s),Album Name,Album Image URL,Track Preview URL,Artist Genres,Label,Artist Name(s)1,tags
0,Justified & Ancient - Stand by the Jams,The KLF,[SongsCollection],https://i.scdn.co/image/ab67616d0000b27355346b...,NaN,"[acid house, ambient house, big beat, hip house]",[JamsCommunications],[The KLF],"[The KLF, SongsCollection, acid house, ambient..."
1,I Know You Want Me (Calle Ocho),Pitbull,[PitbullStarringInRebelution],https://i.scdn.co/image/ab67616d0000b27326d73a...,https://p.scdn.co/mp3-preview/d6f8883fc955cb0e...,"[dance pop, miami hip hop, pop]",[Mr.305/PoloGroundsMusic/JRecords],[Pitbull],"[Pitbull, PitbullStarringInRebelution, dance p..."
2,From the Bottom of My Broken Heart,Britney Spears,[...BabyOneMoreTime(DigitalDeluxeVersion)],https://i.scdn.co/image/ab67616d0000b2738e4986...,https://p.scdn.co/mp3-preview/1de5faef947224dc...,"[dance pop, pop]",[Jive],[Britney Spears],"[Britney Spears, ...BabyOneMoreTime(DigitalDel..."
3,Apeman - 2014 Remastered Version,The Kinks,"[Lolavs.PowermanandtheMoneygoround,Pt.One+Perc...",https://i.scdn.co/image/ab67616d0000b2731e7c53...,https://p.scdn.co/mp3-preview/c4df3a832509cc55...,"[album rock, art rock, british invasion, class...",[SanctuaryRecords],[The Kinks],"[The Kinks, Lolavs.PowermanandtheMoneygoround,..."
4,You Can't Always Get What You Want,The Rolling Stones,[LetItBleed],https://i.scdn.co/image/ab67616d0000b27373d927...,NaN,"[album rock, british invasion, classic rock, r...",[UniversalMusicGroup],[The Rolling Stones],"[The Rolling Stones, LetItBleed, album rock, b..."

In [14]:
df = df[['Track Name','Album Image URL','Track Preview URL','tags','Artist Name(s)']]

In [15]:
df.isna().sum()

Track Name              1
Album Image URL         4
Track Preview URL    2897
tags                    0
Artist Name(s)          1
dtype: int64

In [16]:
df.drop('Track Preview URL',axis=1,inplace=True)

In [17]:
df.isna().sum()

Track Name         1
Album Image URL    4
tags               0
Artist Name(s)     1
dtype: int64

In [18]:
df = df.dropna()

In [19]:
df.isna().sum()

Track Name         0
Album Image URL    0
tags               0
Artist Name(s)     0
dtype: int64

In [20]:
df['tags'] = df['tags'].apply(lambda x:[str(i) for i in x])
df['tags'] = df['tags'].apply(lambda x: ' '.join(x))

In [21]:
df['tags'] = df['tags'].apply(lambda x: x.lower())

In [22]:
df.head()

,Track Name,Album Image URL,tags,Artist Name(s)
0,Justified & Ancient - Stand by the Jams,https://i.scdn.co/image/ab67616d0000b27355346b...,the klf songscollection acid house ambient hou...,The KLF
1,I Know You Want Me (Calle Ocho),https://i.scdn.co/image/ab67616d0000b27326d73a...,pitbull pitbullstarringinrebelution dance pop ...,Pitbull
2,From the Bottom of My Broken Heart,https://i.scdn.co/image/ab67616d0000b2738e4986...,britney spears ...babyonemoretime(digitaldelux...,Britney Spears
3,Apeman - 2014 Remastered Version,https://i.scdn.co/image/ab67616d0000b2731e7c53...,"the kinks lolavs.powermanandthemoneygoround,pt...",The Kinks
4,You Can't Always Get What You Want,https://i.scdn.co/image/ab67616d0000b27373d927...,the rolling stones letitbleed album rock briti...,The Rolling Stones

In [23]:
df.shape

(9995, 4)

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=9995, stop_words='english')

In [25]:
vectors = cv.fit_transform(df['tags']).toarray()

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
simi = cosine_similarity(vectors)

In [28]:
simi[0]

array([1.        , 0.06482037, 0.        , ..., 0.29104275, 0.41176471,
       0.        ])

In [29]:
df[df['Artist Name(s)']=='Michael Jackson']

,Track Name,Album Image URL,tags,Artist Name(s)
241,Heal the World,https://i.scdn.co/image/ab67616d0000b2733b9f8b...,michael jackson dangerous r&b soul epic/legacy,Michael Jackson
430,The Way You Make Me Feel - 2012 Remaster,https://i.scdn.co/image/ab67616d0000b27362e97a...,michael jackson bad(remastered) r&b soul epic/...,Michael Jackson
944,P.Y.T. (Pretty Young Thing),https://i.scdn.co/image/ab67616d0000b2734121fa...,michael jackson thriller25superdeluxeedition r...,Michael Jackson
1293,Man in the Mirror,https://i.scdn.co/image/ab67616d0000b273d05931...,"michael jackson history-past,presentandfuture-...",Michael Jackson
1329,Smooth Criminal - 2012 Remaster,https://i.scdn.co/image/ab67616d0000b2731bb21d...,michael jackson bad25thanniversary r&b soul ep...,Michael Jackson
1591,Come Together,https://i.scdn.co/image/ab67616d0000b273999391...,"michael jackson history-past,presentandfuture-...",Michael Jackson
2302,Blood on the Dance Floor,https://i.scdn.co/image/ab67616d0000b273983d03...,michael jackson bloodonthedancefloor/historyin...,Michael Jackson
2304,You Are Not Alone,https://i.scdn.co/image/ab67616d0000b273d05931...,"michael jackson history-past,presentandfuture-...",Michael Jackson
2490,Remember the Time,https://i.scdn.co/image/ab67616d0000b2733b9f8b...,michael jackson dangerous r&b soul epic/legacy,Michael Jackson
4076,Ben - Single Version,https://i.scdn.co/image/ab67616d0000b273a1f07a...,michael jackson ben r&b soul motown,Michael Jackson
4625,Bad,https://i.scdn.co/image/ab67616d0000b273d05931...,"michael jackson history-past,presentandfuture-...",Michael Jackson
4736,Black or White - Single Version,https://i.scdn.co/image/ab67616d0000b273ed1c30...,michael jackson theessentialmichaeljackson r&b...,Michael Jackson
5405,You Are Not Alone - Single Version,https://i.scdn.co/image/ab67616d0000b273ed1c30...,michael jackson theessentialmichaeljackson r&b...,Michael Jackson
5785,They Don't Care About Us,https://i.scdn.co/image/ab67616d0000b273d05931...,"michael jackson history-past,presentandfuture-...",Michael Jackson
6157,In the Closet - Single Version,https://i.scdn.co/image/ab67616d0000b273ed1c30...,michael jackson theessentialmichaeljackson r&b...,Michael Jackson
6366,Billie Jean,https://i.scdn.co/image/ab67616d0000b2734121fa...,michael jackson thriller25superdeluxeedition r...,Michael Jackson
7848,Rock with You - Single Version,https://i.scdn.co/image/ab67616d0000b273702729...,michael jackson offthewall r&b soul epic,Michael Jackson
7943,Thriller,https://i.scdn.co/image/ab67616d0000b2734121fa...,michael jackson thriller25superdeluxeedition r...,Michael Jackson
8692,Don't Stop 'Til You Get Enough,https://i.scdn.co/image/ab67616d0000b273702729...,michael jackson offthewall r&b soul epic,Michael Jackson
8989,Beat It,https://i.scdn.co/image/ab67616d0000b2734121fa...,michael jackson thriller25superdeluxeedition r...,Michael Jackson
9499,Give In to Me,https://i.scdn.co/image/ab67616d0000b2733b9f8b...,michael jackson dangerous r&b soul epic/legacy,Michael Jackson

In [30]:
def recommend(song):
    song_id = df[df['Track Name']==song].index[0]
    distances = simi[song_id]
    song_list = []
    song_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:11]
    for i in song_list:
        print(df.iloc[i[0]]['Track Name'])

In [31]:
recommend('Without Me')

We Made You
Business
Cleanin' Out My Closet
Sing For The Moment
Not Afraid
Not Afraid
Lose Yourself - From "8 Mile" Soundtrack
Like Toy Soldiers
Not Afraid
Lose Yourself

In [32]:
df.to_csv('final__df.csv')

In [33]:
import pickle 
pickle.dump(simi,open('simis.pkl','wb'))

In [34]:
df['Album Image URL'][0]

'https://i.scdn.co/image/ab67616d0000b27355346bc1f268730f607f9544'